## Less memory 

In [5]:
import numpy as np
import sys

n=list(range(100))
print(n[:10])
sys.getsizeof(n[0])*len(n)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


2800

In [12]:
np_arr=np.arange(100)
np_arr.nbytes

400

## Less Time

In [14]:
x=[1,2,3]
y=[4,5,6]
for x,y in zip(x,y):
    print(x+y)

5
7
9


In [11]:
import time
siz=10000
l1=list(range(siz))
l2=list(range(siz))
start_time=time.time()
l3=[l1+l2 for x,y in zip(l1,l2)]
end_time=time.time()
print("python list took : ", end_time-start_time)

python list took :  5.166304588317871


In [12]:
siz=10000
l1=np.arange(siz)
l2=np.arange(siz)

start_t=time.time()
l3=l1+l2
end_t=time.time()
print("numpy took: ", end_t-start_t)

numpy took:  0.8038699626922607


## convenient to use , with built in functins

In [17]:
x=[1,2,3]
y=[4,5,6]
for x,y in zip(x,y):
    print(x+y)

5
7
9


In [19]:
a=np.arange(4)
b=np.arange(4)
c=np.array([x])
print(c)
a,b

[3]


(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

## Basic Operations

In [20]:
rev=np.array([3,5,7])
rev.ndim

1

In [21]:
rev=np.array([[5,7,23],[8,456,23]])
rev.ndim

2

In [23]:
rev[1,1]

456

In [25]:
rev.itemsize

4

In [26]:
rev.size

6

In [27]:
rev.shape

(2, 3)

In [28]:
np.sort(rev)

array([[  5,   7,  23],
       [  8,  23, 456]])

In [29]:
np.sort(rev,axis=None)

array([  5,   7,   8,  23,  23, 456])

In [30]:
## linearly spaced ,
np.linspace(10,20)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [31]:
rev.flatten()

array([  5,   7,  23,   8, 456,  23])

In [32]:
rev.min()

5

In [33]:
rev.max()

456

In [34]:
rev.sum(axis=1)

array([ 35, 487])

In [35]:
rev.sum(axis=0)

array([ 13, 463,  46])

In [36]:
for row in rev:
    print("row:> ", row)

row:>  [ 5  7 23]
row:>  [  8 456  23]


In [38]:
b=np.array([5,4,2])
np.square(b)

array([25, 16,  4])

In [39]:
np.std(b)

1.247219128924647