## Less memory 

In [2]:
import numpy as np
import sys

n=list(range(100))
print(n[:10])
sys.getsizeof(n[0])*len(n)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


2800

In [12]:
np_arr=np.arange(100)
np_arr.nbytes

400

## Less Time

In [14]:
x=[1,2,3]
y=[4,5,6]
for x,y in zip(x,y):
    print(x+y)

5
7
9


In [11]:
import time
siz=10000
l1=list(range(siz))
l2=list(range(siz))
start_time=time.time()
l3=[l1+l2 for x,y in zip(l1,l2)]
end_time=time.time()
print("python list took : ", end_time-start_time)

python list took :  5.166304588317871


In [12]:
siz=10000
l1=np.arange(siz)
l2=np.arange(siz)

start_t=time.time()
l3=l1+l2
end_t=time.time()
print("numpy took: ", end_t-start_t)

numpy took:  0.8038699626922607


## convenient to use , with built in functins

In [17]:
x=[1,2,3]
y=[4,5,6]
for x,y in zip(x,y):
    print(x+y)

5
7
9


In [19]:
a=np.arange(4)
b=np.arange(4)
c=np.array([x])
print(c)
a,b

[3]


(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

## Basic Operations

In [20]:
rev=np.array([3,5,7])
rev.ndim

1

In [21]:
rev=np.array([[5,7,23],[8,456,23]])
rev.ndim

2

In [23]:
rev[1,1]

456

In [25]:
rev.itemsize

4

In [26]:
rev.size

6

In [27]:
rev.shape

(2, 3)

In [28]:
np.sort(rev)

array([[  5,   7,  23],
       [  8,  23, 456]])

In [29]:
np.sort(rev,axis=None)

array([  5,   7,   8,  23,  23, 456])

In [30]:
## linearly spaced ,
np.linspace(10,20)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [31]:
rev.flatten()

array([  5,   7,  23,   8, 456,  23])

In [32]:
rev.min()

5

In [33]:
rev.max()

456

In [34]:
rev.sum(axis=1)

array([ 35, 487])

In [35]:
rev.sum(axis=0)

array([ 13, 463,  46])

In [36]:
for row in rev:
    print("row:> ", row)

row:>  [ 5  7 23]
row:>  [  8 456  23]


In [38]:
b=np.array([5,4,2])
np.square(b)

array([25, 16,  4])

In [39]:
np.std(b)

1.247219128924647

## Matrix Operations

In [43]:
q1=np.array([[200,220,250],
             [150,180,210],
             [300,330,360]
            ])

q2=np.array([[190,231,259],
             [155,192,222],
             [310,340,375]
            ])
q1+q2

array([[390, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [41]:
q2-q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [44]:
print("Percentage increase in next quarter.")
(q2-q1)*100/q1

Percentage increase in next quarter.


array([[-5.        ,  5.        ,  3.6       ],
       [ 3.33333333,  6.66666667,  5.71428571],
       [ 3.33333333,  3.03030303,  4.16666667]])

In [45]:
prices=np.array([[4,23,6],
                 [6,2,343],
                 [8,6,44]
                ])

In [47]:
q1_rev=prices*q1
print(q1_rev)

[[  800  5060  1500]
 [  900   360 72030]
 [ 2400  1980 15840]]


In [48]:
q1_dis=q1_rev*0.2
print(q1_dis)

[[  160.  1012.   300.]
 [  180.    72. 14406.]
 [  480.   396.  3168.]]


In [49]:
net_q1_rev=q1_rev-q1_dis
print(net_q1_rev)

[[  640.  4048.  1200.]
 [  720.   288. 57624.]
 [ 1920.  1584. 12672.]]


In [50]:
np.sum(net_q1_rev)

80696.0

## Housing Price Prediction

In [51]:
features=np.array([[2000,3],
                  [1800,2]])
weights=np.array([150,50000])
np.dot(features,weights)

array([450000, 370000])

In [53]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.cross(a,b)

array([-3,  6, -3])

## Slicing and Stacking

In [54]:
b=np.array([[4,32,7],
            [7,56,23],
            [8,767,4]
           ])
b[1,2]

23

In [55]:
b[0:,1:]

array([[ 32,   7],
       [ 56,  23],
       [767,   4]])

In [56]:
b[-1,0:2]

array([  8, 767])

## Vstack , Hstack

In [3]:
# Customer ID, Name
c = np.array([
    [101, 'Mira'],
    [102, 'Abdul'],
    [103, 'Andrea']
])
# Customer Id, Purchase Amount, Purchase Date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
])

In [4]:
# concatenating metrices
np.hstack((c,d))              # horizontally

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-01']], dtype='<U32')

In [8]:
e = np.array([
    [104, 'Venkat'],
    [105, 'John'],
    [106, 'Kathy'],
])
np.vstack((c,e))

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U11')

In [7]:
# vertically
#np.vstack((c,e))
np.vstack((c,d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

## vsplit , hsplit

In [61]:
transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])


In [62]:
a,b=np.hsplit(transactions,[2])

In [63]:
a

array([['101', 'Mohan'],
       ['102', 'Bob'],
       ['103', 'Fatima'],
       ['104', 'David'],
       ['105', 'Aryan']], dtype='<U32')

In [64]:
b

array([['250.5', '2023-08-01'],
       ['150.0', '2023-08-02'],
       ['300.75', '2023-08-01'],
       ['400.2', '2023-08-03'],
       ['330.1', '2023-08-04']], dtype='<U32')

In [65]:
c,d=np.vsplit(transactions,[3])

In [66]:
c

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01']], dtype='<U32')

In [67]:
d

array([['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

## Boolean Operation

In [68]:
monthly_sales=np.array([56,463,34,766,78])
result=monthly_sales<100
result

array([ True, False,  True, False,  True])

In [69]:
monthly_sales[result]

array([56, 34, 78])

## Argmax for indexing

In [70]:
# fetching index of max value in array
mx_index=np.argmax(monthly_sales)
monthly_sales[mx_index]

766

In [71]:
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [76]:
mx_t_index=np.argmax(transactions[:,2].astype(float))
print(mx_t_index)
print(transactions[1])
transactions[mx_t_index]

3
['102' 'Bob' '150.0' '2023-08-02']


array(['104', 'David', '400.2', '2023-08-03'], dtype='<U32')

## applying condition in bracket

In [78]:
transactions[transactions[:,0]=='103']

array([['103', 'Fatima', '300.75', '2023-08-01']], dtype='<U32')